import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  Locale _currentLocale = const Locale('en');

  Locale get currentLocale => _currentLocale;

  static final LanguageService _instance = LanguageService._internal();

  factory LanguageService() {
    return _instance;
  }

  LanguageService._internal() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final String? languageCode = prefs.getString('language_code');
    if (languageCode != null) {
      _currentLocale = Locale(languageCode);
      notifyListeners();
    }
  }

  Future<void> changeLanguage(String languageCode) async {
    _currentLocale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }
}

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'dashboard': 'Dashboard',
      'logout': 'Logout',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'hello': 'Hello',
      'welcome': 'Welcome',
      'class': 'Class',
      'subjects': 'Subjects',
      'chat': 'Chat',
      'profile': 'Profile',
      'dailyStreak': 'Daily Streak 🔥',
      'days': 'Days',
      'lastChapter': 'Last Chapter: 65% Completed',
      'recentActivity': 'Recent Activity',
      'quickActions': 'Quick Actions',
      'askAiDoubt': 'Ask AI Doubt',
      'yourSubjects': 'Your Subjects',
      'noSubjects': 'No subjects found',
      'chapters': 'Chapters',
      'watchVideo': 'Watch Video',
      'readNotes': 'Read Notes',
      'takeQuiz': 'Take Quiz',
      'smartSummary': 'Smart Summary',
      'aiDoubtSolver': 'AI Doubt Solver',
      'askDoubt': 'Ask a doubt...',
      'thinking': 'Thinking...',
      'aiCompanion': 'AI Companion',
      'offlineMode': 'Offline Mode',
      'askAboutChapter': 'Ask about a chapter...',
      'login': 'Login',
      'signup': 'Sign Up',
      'enterName': 'Enter Name',
      'enterClass': 'Enter Class',
      'letsGo': "Let's Go",
      'mathematics': 'Mathematics',
      'science': 'Science',
      'history': 'History',
      'english': 'English',
      'hindi': 'Hindi',
      'marathi': 'Marathi',
      'algebraQuiz': 'Algebra Basics Quiz',
      'scienceChapter': 'Science Chapter 2',
      'historyTimeline': 'History Timeline',
      'welcomeBack': 'Welcome Back!',
      'loginSubtitle': 'Login to continue learning',
      'phoneNumber': 'Phone Number',
      'getOtp': 'Get OTP',
      'noAccount': "Don't have an account?",
      'createAccount': 'Create Account',
      'fullName': 'Full Name',
      'verifyContinue': 'Verify & Continue',
      // --- EXTENDED LOCALIZATION ---
      'study': 'Study',
      'quizzes': 'Quizzes',
      'mentor': 'Mentor',
      'profile': 'Profile',
      'profileComingSoon': 'Profile Settings Coming Soon',
      'practiceArena': 'Practice Arena',
      'recommendedForYou': 'Recommended for You',
      'basedOnActivity': 'BASED ON YOUR ACTIVITY',
      'quickTest': 'Quick 10 min test • 10 Questions',
      'browseBySubject': 'Browse by Subject',
      'selectChapter': 'Select a chapter to practice',
      'aiQuizAvailable': 'AI Quiz Available',
      'standardPractice': 'Standard Practice',
      'noQuizGenerated': 'No quiz generated for this chapter yet.',
      'mentorship': 'Mentorship',
      'myMentor': 'My Mentor',
      'mentorshipLocked': 'Mentorship Locked',
      'unlockMentorship': 'Find a mentor to unlock exclusive features like 1:1 meetings, doubt solving, and more.',
      'findMentor': 'Find a Mentor',
      'pendingRequests': 'You have pending request(s)',
      'withdraw': 'Withdraw',
      'subjectExpert': 'Subject Expert',
      'meeting': '1:1 Meeting',
      'resources': 'Resources',
      'disconnectMentor': 'Disconnect Mentor',
      'disconnectConfirm': 'Are you sure you want to disconnect? You will lose access to their resources.',
      'cancel': 'Cancel',
      'disconnect': 'Disconnect',
      'startMeeting': 'Start 1:1 Meeting',
      'initiatingCall': 'Initiating video call...',
      'close': 'Close',
      'mentorDisconnected': 'Mentor disconnected successfully',
      'requestWithdrawn': 'Request withdrawn successfully',
      'search': 'Search...',
      'all': 'All',
      'physics': 'Physics',
      'maths': 'Maths',
      'chemistry': 'Chemistry',
      'biology': 'Biology',
      'noMentorsFound': 'No mentors found.',
      'connect': 'Connect',
      'requestSent': 'Request sent!',
      'failedToSend': 'Failed to send request',
      'offlineRequestQueued': 'Offline: Request queued.',
      'recentActivityTitle': 'Recent Activity',
      'noRecentActivity': 'No recent activity',
      // User Name Transliteration (Demo)
      'user_Atharva': 'Atharva',
    },
    'hi': {
      'dashboard': 'डैशबोर्ड',
      'logout': 'लॉग आउट',
      'darkMode': 'डार्क मोड',
      'language': 'भाषा',
      'selectLanguage': 'भाषा चुनें',
      'hello': 'नमस्ते',
      'welcome': 'स्वागत है',
      'class': 'कक्षा',
      'subjects': 'विषय',
      'chat': 'चैट',
      'profile': 'प्रोफ़ाइल',
      'dailyStreak': 'दैनिक स्ट्रीक 🔥',
      'days': 'दिन',
      'lastChapter': 'अंतिम अध्याय: 65% पूर्ण',
      'recentActivity': 'हाल की गतिविधि',
      'quickActions': 'त्वरित कार्रवाई',
      'askAiDoubt': 'AI से पूछें',
      'yourSubjects': 'आपके विषय',
      'noSubjects': 'कोई विषय नहीं मिला',
      'chapters': 'अध्याय',
      'watchVideo': 'वीडियो देखें',
      'readNotes': 'नोट्स पढ़ें',
      'takeQuiz': 'क्विज़ लें',
      'smartSummary': 'स्मार्ट सारांश',
      'aiDoubtSolver': 'AI शंका समाधान',
      'askDoubt': 'एक शंका पूछें...',
      'thinking': 'सोच रहा हूँ...',
      'aiCompanion': 'AI साथी',
      'offlineMode': 'ऑफ़लाइन मोड',
      'askAboutChapter': 'अध्याय के बारे में पूछें...',
      'login': 'लॉग इन',
      'signup': 'साइन अप',
      'enterName': 'नाम दर्ज करें',
      'enterClass': 'कक्षा दर्ज करें',
      'letsGo': 'चलो चलें',
      'mathematics': 'गणित',
      'science': 'विज्ञान',
      'history': 'इतिहास',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'algebraQuiz': 'बीजगणित प्रश्नोत्तरी',
      'scienceChapter': 'विज्ञान अध्याय 2',
      'historyTimeline': 'इतिहास समयरेखा',
      'welcomeBack': 'वापसी पर स्वागत है!',
      'loginSubtitle': 'सीखना जारी रखने के लिए लॉगिन करें',
      'phoneNumber': 'फ़ोन नंबर',
      'getOtp': 'OTP प्राप्त करें',
      'noAccount': 'खाता नहीं है?',
      'createAccount': 'खाता बनाएं',
      'fullName': 'पूरा नाम',
      'verifyContinue': 'सत्यापित करें और जारी रखें',
      // --- EXTENDED LOCALIZATION ---
      'study': 'अध्ययन',
      'quizzes': 'क्विज़',
      'mentor': 'मेंटर',
      'profile': 'प्रोफ़ाइल',
      'profileComingSoon': 'प्रोफ़ाइल सेटिंग्स जल्द आ रही हैं',
      'practiceArena': 'अभ्यास क्षेत्र',
      'recommendedForYou': 'आपके लिए अनुशंसित',
      'basedOnActivity': 'आपकी गतिविधि के आधार पर',
      'quickTest': 'त्वरित 10 मिनट का टेस्ट • 10 प्रश्न',
      'browseBySubject': 'विषय के अनुसार ब्राउज़ करें',
      'selectChapter': 'अभ्यास करने के लिए एक अध्याय चुनें',
      'aiQuizAvailable': 'AI क्विज़ उपलब्ध',
      'standardPractice': 'मानक अभ्यास',
      'noQuizGenerated': 'अभी तक इस अध्याय के लिए कोई क्विज़ नहीं बना है।',
      'mentorship': 'मेंटरशिप',
      'myMentor': 'मेरा मेंटर',
      'mentorshipLocked': 'मेंटरशिप लॉक है',
      'unlockMentorship': '1:1 मीटिंग, शंका समाधान और अधिक सुविधाओं को अनलॉक करने के लिए एक मेंटर खोजें।',
      'findMentor': 'एक मेंटर खोजें',
      'pendingRequests': 'आपके पास लंबित अनुरोध हैं',
      'withdraw': 'वापस लें',
      'subjectExpert': 'विषय विशेषज्ञ',
      'meeting': '1:1 मीटिंग',
      'resources': 'संसाधन',
      'disconnectMentor': 'मेंटर को डिस्कनेक्ट करें',
      'disconnectConfirm': 'क्या आप वाकई डिस्कनेक्ट करना चाहते हैं? आप उनके संसाधनों तक पहुंच खो देंगे।',
      'cancel': 'रद्द करें',
      'disconnect': 'डिस्कनेक्ट करें',
      'startMeeting': '1:1 मीटिंग शुरू करें',
      'initiatingCall': 'वीडियो कॉल शुरू हो रहा है...',
      'close': 'बंद करें',
      'mentorDisconnected': 'मेंटर सफलतापूर्वक डिस्कनेक्ट हो गया',
      'requestWithdrawn': 'अनुरोध सफलतापूर्वक वापस ले लिया गया',
      'search': 'खोजें...',
      'all': 'सभी',
      'physics': 'भौतिकी',
      'maths': 'गणित',
      'chemistry': 'रसायन विज्ञान',
      'biology': 'जीवविज्ञान',
      'noMentorsFound': 'कोई मेंटर नहीं मिला।',
      'connect': 'कनेक्ट करें',
      'requestSent': 'अनुरोध भेजा गया!',
      'failedToSend': 'अनुरोध भेजने में विफल',
      'offlineRequestQueued': 'ऑफ़लाइन: अनुरोध कतार में है।',
      'recentActivityTitle': 'हाल की गतिविधि',
      'noRecentActivity': 'कोई हालिया गतिविधि नहीं',
      'user_Atharva': 'अथर्व',
    },
    'mr': {
      'dashboard': 'डॅशबोर्ड',
      'logout': 'बाहेर पडा',
      'darkMode': 'डार्क मोड',
      'language': 'भाषा',
      'selectLanguage': 'भाषा निवडा',
      'hello': 'नमस्कार',
      'welcome': 'स्वागत आहे',
      'class': 'इयत्ता',
      'subjects': 'विषय',
      'chat': 'चॅट',
      'profile': 'प्रोफाइल',
      'dailyStreak': 'दैनिक स्ट्रीक 🔥',
      'days': 'दिवस',
      'lastChapter': 'शेवटचा धडा: 65% पूर्ण',
      'recentActivity': 'अलीकडील क्रियाकलाप',
      'quickActions': 'जलद क्रिया',
      'askAiDoubt': 'AI ला विचारा',
      'yourSubjects': 'तुमचे विषय',
      'noSubjects': 'कोणतेही विषय आढळले नाहीत',
      'chapters': 'धडे',
      'watchVideo': 'व्हिडिओ पहा',
      'readNotes': 'नोट्स वाचा',
      'takeQuiz': 'क्विझ घ्या',
      'smartSummary': 'स्मार्ट सारांश',
      'aiDoubtSolver': 'AI शंका निवारण',
      'askDoubt': 'शंका विचारा...',
      'thinking': 'विचार करत आहे...',
      'aiCompanion': 'AI सोबती',
      'offlineMode': 'ऑफलाइन मोड',
      'askAboutChapter': 'धड्याबद्दल विचारा...',
      'login': 'लॉग इन',
      'signup': 'साइन अप',
      'enterName': 'नाव प्रविष्ट करा',
      'enterClass': 'इयत्ता प्रविष्ट करा',
      'letsGo': 'चला जाऊया',
      'mathematics': 'गणित',
      'science': 'विज्ञान',
      'history': 'इतिहास',
      'english': 'इंग्रजी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'algebraQuiz': 'बीजगणित क्विझ',
      'scienceChapter': 'विज्ञान धडा 2',
      'historyTimeline': 'इतिहास कालरेषा',
      'welcomeBack': 'पुन्हा स्वागत आहे!',
      'loginSubtitle': 'शिकणे सुरू ठेवण्यासाठी लॉगिन करा',
      'phoneNumber': 'फोन नंबर',
      'getOtp': 'OTP मिळवा',
      'noAccount': 'खाते नाही?',
      'createAccount': 'खाते तयार करा',
      'fullName': 'पूर्ण नाव',
      'verifyContinue': 'सत्यापित करा आणि पुढे जा',
      // --- EXTENDED LOCALIZATION ---
      'study': 'अभ्यास',
      'quizzes': 'क्विझ',
      'mentor': 'मेंटर',
      'profile': 'प्रोफाइल',
      'profileComingSoon': 'प्रोफाइल सेटिंग्ज लवकरच येत आहेत',
      'practiceArena': 'सराव क्षेत्र',
      'recommendedForYou': 'तुमच्यासाठी शिफारस केलेले',
      'basedOnActivity': 'तुमच्या क्रियाकलापावर आधारित',
      'quickTest': 'जलद 10 मिनिटांची चाचणी • 10 प्रश्न',
      'browseBySubject': 'विषयानुसार ब्राउझ करा',
      'selectChapter': 'सराव करण्यासाठी धडा निवडा',
      'aiQuizAvailable': 'AI क्विझ उपलब्ध',
      'standardPractice': 'मानक सराव',
      'noQuizGenerated': 'या धड्यासाठी अद्याप कोणतीही क्विझ तयार केलेली नाही.',
      'mentorship': 'मेंटरशिप',
      'myMentor': 'माझा मेंटर',
      'mentorshipLocked': 'मेंटरशिप लॉक आहे',
      'unlockMentorship': '1:1 मीटिंग, शंका निवारण आणि अधिक वैशिष्ट्ये अनलॉक करण्यासाठी मेंटर शोधा.',
      'findMentor': 'मेंटर शोधा',
      'pendingRequests': 'तुमच्याकडे प्रलंबित विनंत्या आहेत',
      'withdraw': 'मागे घ्या',
      'subjectExpert': 'विषय तज्ञ',
      'meeting': '1:1 मीटिंग',
      'resources': 'संसाधने',
      'disconnectMentor': 'मेंटरला डिस्कनेक्ट करा',
      'disconnectConfirm': 'तुम्हाला नक्की डिस्कनेक्ट करायचे आहे का? तुम्ही त्यांच्या संसाधनांमध्ये प्रवेश गमावाल.',
      'cancel': 'रद्द करा',
      'disconnect': 'डिस्कनेक्ट करा',
      'startMeeting': '1:1 मीटिंग सुरू करा',
      'initiatingCall': 'व्हिडिओ कॉल सुरू करत आहे...',
      'close': 'बंद करा',
      'mentorDisconnected': 'मेंटर यशस्वीरित्या डिस्कनेक्ट झाला',
      'requestWithdrawn': 'विनंती यशस्वीरित्या मागे घेतली',
      'search': 'शोधा...',
      'all': 'सर्व',
      'physics': 'भौतिकशास्त्र',
      'maths': 'गणित',
      'chemistry': 'रसायनशास्त्र',
      'biology': 'जीवशास्त्र',
      'noMentorsFound': 'कोणतेही मेंटर सापडले नाहीत.',
      'connect': 'कनेक्ट करा',
      'requestSent': 'विनंती पाठवली!',
      'failedToSend': 'विनंती पाठवण्यात अयशस्वी',
      'offlineRequestQueued': 'ऑफलाइन: विनंती रांगेत आहे.',
      'recentActivityTitle': 'अलीकडील क्रियाकलाप',
      'noRecentActivity': 'कोणतीही अलीकडील क्रियाकलाप नाही',
      'user_Atharva': 'अथर्व',
    },
    'ta': {
      'dashboard': 'டாஷ்போர்டு',
      'logout': 'வெளியேறு',
      'darkMode': 'டார்க் மோட்',
      'language': 'மொழி',
      'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'hello': 'வணக்கம்',
      'welcome': 'வரவேற்கிறோம்',
      'class': 'வகுப்பு',
      'subjects': 'பாடங்கள்',
      'chat': 'அரட்டை',
      'profile': 'சுயவிவரம்',
      'dailyStreak': 'தினசரி ஸ்ட்ரீக் 🔥',
      'days': 'நாட்கள்',
      'lastChapter': 'கடைசி பாடம்: 65% முடிந்தது',
      'recentActivity': 'சமீபத்திய செயல்பாடு',
      'quickActions': 'விரைவான செயல்கள்',
      'askAiDoubt': 'AI ஐக் கேளுங்கள்',
      'yourSubjects': 'உங்கள் பாடங்கள்',
      'noSubjects': 'பாடங்கள் எதுவும் இல்லை',
      'chapters': 'பாடங்கள்',
      'watchVideo': 'வீடியோவைப் பாருங்கள்',
      'readNotes': 'குறிப்புகளைப் படியுங்கள்',
      'takeQuiz': 'வினாடி வினா எடுங்கள்',
      'smartSummary': 'ஸ்மார்ட் சுருக்கம்',
      'aiDoubtSolver': 'AI சந்தேகம் தீர்ப்பவர்',
      'askDoubt': 'சந்தேகம் கேளுங்கள்...',
      'thinking': 'யோசிக்கிறது...',
      'aiCompanion': 'AI துணை',
      'offlineMode': 'ஆஃப்லைன் பயன்முறை',
      'askAboutChapter': 'பாடத்தைப் பற்றி கேளுங்கள்...',
      'login': 'உள்நுழைய',
      'signup': 'பதிவு செய்யவும்',
      'enterName': 'பெயரை உள்ளிடவும்',
      'enterClass': 'வகுப்பை உள்ளிடவும்',
      'letsGo': 'செல்வோம்',
      'mathematics': 'கணிதம்',
      'science': 'அறிவியல்',
      'history': 'வரலாறு',
      'english': 'ஆங்கிலம்',
      'hindi': 'இந்தி',
      'marathi': 'மராத்தி',
      'algebraQuiz': 'இயற்கணித வினாடி வினா',
      'scienceChapter': 'அறிவியல் பாடம் 2',
      'historyTimeline': 'வரலாற்று காலவரிசை',
      'welcomeBack': 'மீண்டும் வரவேற்கிறோம்!',
      'loginSubtitle': 'கற்றலைத் தொடர உள்நுழையவும்',
      'phoneNumber': 'தொலைபேசி எண்',
      'getOtp': 'OTP பெறவும்',
      'noAccount': 'கணக்கு இல்லையா?',
      'createAccount': 'கணக்கை உருவாக்கவும்',
      'fullName': 'முழு பெயர்',
      'verifyContinue': 'சரிபார்த்து தொடரவும்',
    },
    'gu': {
      'dashboard': 'ડેશબોર્ડ',
      'logout': 'લોગ આઉટ',
      'darkMode': 'ડાર્ક મોડ',
      'language': 'ભાષા',
      'selectLanguage': 'ભાષા પસંદ કરો',
      'hello': 'નમસ્તે',
      'welcome': 'સ્વાગત છે',
      'class': 'વર્ગ',
      'subjects': 'વિષયો',
      'chat': 'ચેટ',
      'profile': 'પ્રોફાઇલ',
      'dailyStreak': 'દૈનિક સ્ટ્રીક 🔥',
      'days': 'દિવસો',
      'lastChapter': 'છેલ્લો પ્રકરણ: 65% પૂર્ણ',
      'recentActivity': 'તાજેતરની પ્રવૃત્તિ',
      'quickActions': 'ઝડપી ક્રિયાઓ',
      'askAiDoubt': 'AI ને પૂછો',
      'yourSubjects': 'તમારા વિષયો',
      'noSubjects': 'કોઈ વિષયો મળ્યા નથી',
      'chapters': 'પ્રકરણો',
      'watchVideo': 'વિડિઓ જુઓ',
      'readNotes': 'નોંધો વાંચો',
      'takeQuiz': 'ક્વિઝ લો',
      'smartSummary': 'સ્માર્ટ સારાંશ',
      'aiDoubtSolver': 'AI શંકા ઉકેલનાર',
      'askDoubt': 'શંકા પૂછો...',
      'thinking': 'વિચારી રહ્યું છે...',
      'aiCompanion': 'AI સાથી',
      'offlineMode': 'ઓફલાઇન મોડ',
      'askAboutChapter': 'પ્રકરણ વિશે પૂછો...',
      'login': 'લોગ ઇન',
      'signup': 'સાઇન અપ',
      'enterName': 'નામ દાખલ કરો',
      'enterClass': 'વર્ગ દાખલ કરો',
      'letsGo': 'ચાલો જઈએ',
      'mathematics': 'ગણિત',
      'science': 'વિજ્ઞાન',
      'history': 'ઇતિહાસ',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'marathi': 'મરાઠી',
      'algebraQuiz': 'બીજગણિત ક્વિઝ',
      'scienceChapter': 'વિજ્ઞાન પ્રકરણ 2',
      'historyTimeline': 'ઇતિહાસ સમયરેખા',
      'welcomeBack': 'ફરી સ્વાગત છે!',
      'loginSubtitle': 'શીખવાનું ચાલુ રાખવા માટે લોગિન કરો',
      'phoneNumber': 'ફોન નંબર',
      'getOtp': 'OTP મેળવો',
      'noAccount': 'ખાતું નથી?',
      'createAccount': 'ખાતું બનાવો',
      'fullName': 'પૂરું નામ',
      'verifyContinue': 'ચકાસો અને ચાલુ રાખો',
    },
    'bn': {
      'dashboard': 'ড্যাশবোর্ড',
      'logout': 'লগ আউট',
      'darkMode': 'ডার্ক মোড',
      'language': 'ভাষা',
      'selectLanguage': 'ভাষা নির্বাচন করুন',
      'hello': 'হ্যালো',
      'welcome': 'স্বাগতম',
      'class': 'শ্রেণী',
      'subjects': 'বিষয়',
      'chat': 'চ্যাট',
      'profile': 'প্রোফাইল',
      'dailyStreak': 'দৈনিক স্ট্রিক 🔥',
      'days': 'দিন',
      'lastChapter': 'শেষ অধ্যায়: 65% সম্পন্ন',
      'recentActivity': 'সাম্প্রতিক কার্যকলাপ',
      'quickActions': 'দ্রুত পদক্ষেপ',
      'askAiDoubt': 'AI কে জিজ্ঞাসা করুন',
      'yourSubjects': 'আপনার বিষয়',
      'noSubjects': 'কোন বিষয় পাওয়া যায়নি',
      'chapters': 'অধ্যায়',
      'watchVideo': 'ভিডিও দেখুন',
      'readNotes': 'নোট পড়ুন',
      'takeQuiz': 'কুইজ নিন',
      'smartSummary': 'স্মার্ট সারাংশ',
      'aiDoubtSolver': 'AI সন্দেহ সমাধানকারী',
      'askDoubt': 'একটি সন্দেহ জিজ্ঞাসা করুন...',
      'thinking': 'ভাবছে...',
      'aiCompanion': 'AI সঙ্গী',
      'offlineMode': 'অফলাইন মোড',
      'askAboutChapter': 'অধ্যায় সম্পর্কে জিজ্ঞাসা করুন...',
      'login': 'লগ ইন',
      'signup': 'সাইন আপ',
      'enterName': 'নাম লিখুন',
      'enterClass': 'শ্রেণী লিখুন',
      'letsGo': 'চলো যাই',
      'mathematics': 'গণিত',
      'science': 'বিজ্ঞান',
      'history': 'ইতিহাস',
      'english': 'ইংরেজি',
      'hindi': 'হিন্দি',
      'marathi': 'মারাঠি',
      'algebraQuiz': 'বীজগণিত কুইজ',
      'scienceChapter': 'বিজ্ঞান অধ্যায় 2',
      'historyTimeline': 'ইতিহাস সময়রেখা',
      'welcomeBack': 'স্বাগতম!',
      'loginSubtitle': 'শেখা চালিয়ে যেতে লগইন করুন',
      'phoneNumber': 'ফোন নম্বর',
      'getOtp': 'OTP পান',
      'noAccount': 'অ্যাকাউন্ট নেই?',
      'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
      'fullName': 'পুরো নাম',
      'verifyContinue': 'যাচাই করুন এবং চালিয়ে যান',
    },
    'te': {
      'dashboard': 'డాష్‌బోర్డ్',
      'logout': 'లాగ్ అవుట్',
      'darkMode': 'డార్క్ మోడ్',
      'language': 'భాష',
      'selectLanguage': 'భాషను ఎంచుకోండి',
      'hello': 'హలో',
      'welcome': 'స్వాగతం',
      'class': 'తరగతి',
      'subjects': 'విషయాలు',
      'chat': 'చాట్',
      'profile': 'ప్రొఫైల్',
      'dailyStreak': 'రోజువారీ స్ట్రీక్ 🔥',
      'days': 'రోజులు',
      'lastChapter': 'చివరి అధ్యాయం: 65% పూర్తయింది',
      'recentActivity': 'ఇటీవలి కార్యాచరణ',
      'quickActions': 'త్వరిత చర్యలు',
      'askAiDoubt': 'AI ని అడగండి',
      'yourSubjects': 'మీ విషయాలు',
      'noSubjects': 'ఏ విషయాలు కనుగొనబడలేదు',
      'chapters': 'అధ్యాయాలు',
      'watchVideo': 'వీడియో చూడండి',
      'readNotes': 'గమనికలు చదవండి',
      'takeQuiz': 'క్విజ్ తీసుకోండి',
      'smartSummary': 'స్మార్ట్ సారాంశం',
      'aiDoubtSolver': 'AI సందేహ నివారణ',
      'askDoubt': 'సందేహం అడగండి...',
      'thinking': 'ఆలోచిస్తోంది...',
      'aiCompanion': 'AI సహచరుడు',
      'offlineMode': 'ఆఫ్‌లైన్ మోడ్',
      'askAboutChapter': 'అధ్యాయం గురించి అడగండి...',
      'login': 'లాగిన్',
      'signup': 'సైన్ అప్',
      'enterName': 'పేరు నమోదు చేయండి',
      'enterClass': 'తరగతి నమోదు చేయండి',
      'letsGo': 'వెళ్దాం',
      'mathematics': 'గణితం',
      'science': 'సైన్స్',
      'history': 'చరిత్ర',
      'english': 'ఇంగ్లీష్',
      'hindi': 'హిందీ',
      'marathi': 'మరాఠీ',
      'algebraQuiz': 'ఆల్జీబ్రా క్విజ్',
      'scienceChapter': 'సైన్స్ అధ్యాయం 2',
      'historyTimeline': 'చరిత్ర కాలక్రమం',
      'welcomeBack': 'తిరిగి స్వాగతం!',
      'loginSubtitle': 'నేర్చుకోవడం కొనసాగించడానికి లాగిన్ చేయండి',
      'phoneNumber': 'ఫోన్ నంబర్',
      'getOtp': 'OTP పొందండి',
      'noAccount': 'ఖాతా లేదా?',
      'createAccount': 'ఖాతా సృష్టించండి',
      'fullName': 'పూర్తి పేరు',
      'verifyContinue': 'ధృవీకరించండి మరియు కొనసాగండి',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String getLanguageName(String code) {
    switch (code) {
      case 'hi': return 'Hindi';
      case 'mr': return 'Marathi';
      case 'ta': return 'Tamil';
      case 'gu': return 'Gujarati';
      case 'bn': return 'Bangla';
      case 'te': return 'Telugu';
      default: return 'English';
    }
  }

  String getUserName(String originalName) {
    // Demo Transliteration for specific user
    if (originalName == 'Atharva') {
      return translate('user_Atharva');
    }
    return originalName;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'mr', 'ta', 'gu', 'bn', 'te']
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
